apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-workflow1
  labels:
    app: spring-petclinic-workflow1
    kubernetes.azure.com/generator: devhub
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-workflow1
  template:
    metadata:
      labels:
        app: spring-petclinic-workflow1
    spec:
      containers:
        - name: spring-petclinic-workflow1
          image: acrworkflow1725261107134.azurecr.io/image-workflow-1725261107134:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
