apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-workflow1
  namespace: petclinic
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic-workflow1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080